columns:
  - customerID: category
  - gender: category
  - SeniorCitizen: int
  - Partner: category
  - Dependents: category
  - tenure: int
  - PhoneService: category
  - MultipleLines: category
  - InternetService: category
  - OnlineSecurity: category
  - OnlineBackup: category
  - DeviceProtection: category
  - TechSupport: category
  - StreamingTV: category
  - StreamingMovies: category
  - Contract: category
  - PaperlessBilling: category
  - PaymentMethod: category
  - MonthlyCharges: float
  - TotalCharges: float
  - Churn: category
numerical_columns:
  - MonthlyCharges
  - TotalCharges
  - SeniorCitizen
categorical_columns:
  - customerID
  - gender
  - Partner
  - tenure
  - Dependents
  - PhoneService
  - MultipleLines
  - InternetService
  - OnlineSecurity
  - OnlineBackup
  - DeviceProtection
  - TechSupport
  - StreamingTV
  - StreamingMovies
  - Contract
  - PaperlessBilling
  - PaymentMethod

drop_columns:
  - customerID
num_features:
  - MonthlyCharges
  - TotalCharges
or_columns:
  - SeniorCitizen
  - Partner
  - Dependents
  - PhoneService
  - PaperlessBilling
  - tenure
oh_columns:
  - gender
  - MultipleLines
  - InternetService
  - OnlineSecurity
  - OnlineBackup
  - DeviceProtection
  - TechSupport
  - StreamingTV
  - StreamingMovies
  - Contract
  - PaymentMethod
transform_columns:
  - MonthlyCharges
  - TotalCharges